spring.application.name=employee_information_management

# DATABASE CONNECTION
# En local usa los valores por defecto. En Render usa las variables de entorno configuradas en el dashboard.
spring.datasource.url=${DATABASE_URL:jdbc:postgresql://localhost:5432/db_company}
spring.datasource.username=${DATABASE_USERNAME:postgres}
spring.datasource.password=${DATABASE_PASSWORD:Putosql1}
spring.datasource.driver-class-name=${DATABASE_DRIVER:org.postgresql.Driver}

# JPA / HIBERNATE
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# WEB SERVER
spring.main.web-application-type=servlet

# RESEND API
resend.api.key=${RESEND_API_KEY:re_eTnKz8zF_LUcvURkrCX665GQZSZ6Njh1e}