spring.application.name=employee_information_management

# DATABASE CONNECTION
spring.datasource.url=jdbc:postgresql://localhost:5432/db_company
spring.datasource.username=postgres
spring.datasource.password=Putosql1
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / HIBERNATE
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# WEB SERVER
spring.main.web-application-type=servlet

# RESEND API
resend.api.key=re_eTnKz8zF_LUcvURkrCX665GQZSZ6Njh1e

